# Generated by Django 5.2 on 2025-04-07 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hangmansesh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default=None, max_length=25)),
                ('word', models.CharField(default=None)),
                ('nonletters', models.CharField(default=None, max_length=50)),
                ('guesses', models.TextField(default=None)),
                ('lives', models.IntegerField(default=3)),
            ],
        ),
    ]
