# Generated by Django 5.2 on 2025-04-07 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_hangmansesh'),
    ]

    operations = [
        migrations.AddField(
            model_name='hangmansesh',
            name='disp',
            field=models.CharField(default=None),
        ),
    ]
