# Generated by Django 5.2 on 2025-04-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_oretrail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oretrail',
            name='body',
            field=models.TextField(default=None),
        ),
    ]
