# Generated by Django 5.2 on 2025-04-09 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_alter_oretrail_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oregontrailevents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None)),
                ('chances', models.IntegerField()),
                ('numeffect', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Oregontrailstops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=None)),
                ('name', models.CharField(default=None)),
            ],
        ),
        migrations.DeleteModel(
            name='Oretrail',
        ),
    ]
