# Generated by Django 5.2 on 2025-04-16 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_oregontrailevents_oregontrailstops_delete_oretrail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gamename', models.CharField(default=None)),
                ('score', models.IntegerField()),
            ],
        ),
    ]
